import type {
  RecoveryAlternativeV1,
  RecoveryPlanV1,
  RecoveryStepV1,
  RepoSignalsV1,
  VerificationResultV1,
} from '@latchops/schema';

const RULE = '─'.repeat(60);

function section(title: string): string {
  return `\n${title}\n${'-'.repeat(title.length)}`;
}

function indent(text: string, spaces = 2): string {
  const pad = ' '.repeat(spaces);
  return text
    .split('\n')
    .map((line) => (line.length > 0 ? pad + line : line))
    .join('\n');
}

// ---------------- diagnose ----------------

export function renderDiagnose(signals: RepoSignalsV1): string {
  const lines: string[] = [];
  lines.push(RULE);
  lines.push('LatchOps diagnosis');
  lines.push(RULE);

  lines.push(section('State'));
  lines.push(`  ${signals.state}`);

  lines.push(section('Secondary states'));
  lines.push(
    signals.secondaryStates.length > 0
      ? indent(signals.secondaryStates.map((s) => `- ${s}`).join('\n'))
      : '  (none)',
  );

  lines.push(section('Working tree'));
  const w = signals.worktree;
  lines.push(
    `  staged=${w.staged} modified=${w.modified} untracked=${w.untracked} conflicted=${w.conflicted}`,
  );

  lines.push(section('Reasons'));
  lines.push(
    signals.reasons.length > 0
      ? indent(signals.reasons.map((r) => `- ${r}`).join('\n'))
      : '  (none)',
  );

  return lines.join('\n');
}

// ---------------- plan ----------------

export function renderPlan(plan: RecoveryPlanV1, selectedAlternativeId: string | null): string {
  const lines: string[] = [];
  lines.push(RULE);
  lines.push(`LatchOps recovery plan  (generated by ${plan.generatedBy} v${plan.engineVersion})`);
  lines.push(RULE);

  lines.push(section('State'));
  lines.push(`  ${plan.incidentType}`);

  lines.push(section('Risk'));
  lines.push(`  ${plan.risk}`);

  lines.push(section('Summary'));
  lines.push(indent(plan.summary));

  if (plan.manualReviewRequired || plan.incomplete) {
    lines.push(section('Manual review'));
    lines.push(`  manualReviewRequired=${plan.manualReviewRequired} incomplete=${plan.incomplete}`);
  }

  if (plan.preconditions.length > 0) {
    lines.push(section('Preconditions'));
    lines.push(indent(plan.preconditions.map((p) => `- ${p}`).join('\n')));
  }

  if (plan.steps.length > 0) {
    lines.push(section('Steps'));
    for (const step of plan.steps) {
      lines.push(renderStep(step));
    }
  }

  if (plan.alternatives.length > 0) {
    lines.push(section('Recommended path'));
    const rec = plan.alternatives.find((a) => a.recommended) ?? plan.alternatives[0];
    lines.push(`  ${rec.id} — ${rec.title}${rec.recommended ? '  [recommended]' : ''}`);

    lines.push(section('Alternatives'));
    for (const alt of plan.alternatives) {
      lines.push(renderAlternative(alt, selectedAlternativeId));
    }
  }

  const destructive = collectDestructive(plan);
  if (destructive.length > 0) {
    lines.push(section('Destructive operations (require confirmation)'));
    for (const d of destructive) {
      lines.push(`  [!] ${d}`);
    }
  }

  if (plan.warnings.length > 0) {
    lines.push(section('Warnings'));
    lines.push(indent(plan.warnings.map((warning) => `- ${warning}`).join('\n')));
  }

  lines.push(section('Verification'));
  lines.push('  After acting, run: latchops verify --plan <saved-plan.json>');

  return lines.join('\n');
}

function renderStep(step: RecoveryStepV1): string {
  const flags: string[] = [`risk=${step.risk}`];
  if (step.destructive) flags.push('DESTRUCTIVE');
  if (step.requiresConfirmation) flags.push('confirm-required');
  if (step.applicability.optional) flags.push('optional');

  const lines: string[] = [];
  lines.push(`  ${step.order}. ${step.title}  (${flags.join(', ')})`);
  lines.push(`     ${step.description}`);
  for (const cmd of step.commands) {
    const marker = cmd.containsPlaceholder ? ' [placeholder]' : cmd.readOnly ? ' [read-only]' : '';
    lines.push(`       $ ${cmd.display}${marker}`);
  }
  if (step.prerequisites.length > 0) {
    lines.push(`     prerequisites: ${step.prerequisites.join('; ')}`);
  }
  lines.push(`     expected: ${step.expectedOutcome}`);
  lines.push(
    `     undo (${step.undoStrategy.reversibility}${step.undoStrategy.guaranteed ? ', guaranteed' : ', not guaranteed'}): ${step.undoStrategy.description}`,
  );
  if (step.undoStrategy.notes) {
    lines.push(`       note: ${step.undoStrategy.notes}`);
  }
  lines.push(`     verify: ${step.verification.description}`);
  return lines.join('\n');
}

function renderAlternative(alt: RecoveryAlternativeV1, selectedId: string | null): string {
  const selected = selectedId === alt.id ? '  <== selected' : '';
  const lines: string[] = [];
  lines.push(
    `  * ${alt.id} — ${alt.title}  (risk=${alt.risk}${alt.recommended ? ', recommended' : ''})${selected}`,
  );
  lines.push(`    ${alt.description}`);
  lines.push(`    tradeoffs: ${alt.tradeoffs}`);
  for (const step of alt.steps) {
    lines.push(indent(renderStep(step), 2));
  }
  return lines.join('\n');
}

function collectDestructive(plan: RecoveryPlanV1): string[] {
  const out: string[] = [];
  const scan = (steps: RecoveryStepV1[], prefix: string): void => {
    for (const step of steps) {
      if (step.destructive) {
        out.push(`${prefix}${step.title}: ${step.commands.map((c) => c.display).join(' ; ')}`);
      }
    }
  };
  scan(plan.steps, '');
  for (const alt of plan.alternatives) {
    scan(alt.steps, `[${alt.id}] `);
  }
  return out;
}

// ---------------- verify ----------------

export function renderVerify(result: VerificationResultV1): string {
  const lines: string[] = [];
  lines.push(RULE);
  lines.push('LatchOps verification');
  lines.push(RULE);

  lines.push(section('Status'));
  lines.push(`  ${result.status}`);

  lines.push(section('State transition'));
  lines.push(
    `  before=${result.beforeState}  ->  after=${result.afterState}  (incident: ${result.incidentType})`,
  );
  if (result.selectedAlternativeId) {
    lines.push(`  selected alternative: ${result.selectedAlternativeId}`);
  }

  lines.push(section('Reasons'));
  lines.push(
    result.reasons.length > 0
      ? indent(result.reasons.map((r) => `- ${r}`).join('\n'))
      : '  (none)',
  );

  lines.push(section('Changed signals'));
  if (result.changedSignals.length > 0) {
    for (const c of result.changedSignals) {
      lines.push(`  ${c.field}: ${format(c.before)} -> ${format(c.after)}`);
    }
  } else {
    lines.push('  (no tracked signals changed)');
  }

  if (result.remainingIssues.length > 0) {
    lines.push(section('Remaining issues'));
    lines.push(indent(result.remainingIssues.map((r) => `- ${r}`).join('\n')));
  }

  return lines.join('\n');
}

function format(value: unknown): string {
  if (value === null) return 'null';
  if (value === undefined) return 'undefined';
  if (Array.isArray(value)) return `[${value.length}]`;
  return String(value);
}
